import React, { useState, useEffect, useContext, useCallback } from 'react';
import './SalesReport.css';
import { 
  Container, 
  Row, 
  Col, 
  Card, 
  Table, 
  Button, 
  Form, 
  Spinner, 
  Alert,
  Badge,
  Tabs,
  Tab
} from 'react-bootstrap';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { getSalesReport } from '../../api'; // You'll need to create this API function
import { FormatCurrency } from '../../utils/index';
import { UserBusinessContext } from '../../context/UserBusinessContext';
import { FaDownload, FaFilter, FaChartBar, FaReceipt } from 'react-icons/fa';

const SalesReport = () => {
  const [period, setPeriod] = useState('today');
  const [startDate, setStartDate] = useState('');
  const [endDate, setEndDate] = useState('');
  const [reportData, setReportData] = useState({
    summary: {
      totalOrders: 0,
      totalRevenue: 0,
      averageOrderValue: 0,
      ordersCount: 0
    },
    orderBreakdown: [],
    categorySales: [],
    hourlyData: []
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const { business } = useContext(UserBusinessContext);
  const currency = business?.settings?.currency || 'USD';

  const fetchSalesReport = useCallback(async () => {
    setLoading(true);
    setError('');
    try {
      const params = { period };
      if (period === 'custom') {
        params.startDate = startDate;
        params.endDate = endDate;
      }
      const data = await getSalesReport(params);
      
      setReportData({
        summary: {
          totalOrders: data.totalOrders || 0,
          totalRevenue: data.totalRevenue || 0,
          averageOrderValue: data.averageOrderValue || 0,
          ordersCount: data.ordersCount || 0
        },
        orderBreakdown: data.orderBreakdown || [],
        categorySales: data.categorySales || [],
        hourlyData: data.hourlyData || []
      });
    } catch (err) {
      console.error('Failed to fetch sales report:', err);
      setError('Unable to load sales report. Please try again later.');
    } finally {
      setLoading(false);
    }
  }, [period, startDate, endDate]);

  useEffect(() => {
    if (period !== 'custom') {
      fetchSalesReport();
    }
  }, [period, fetchSalesReport]);

  const handleCustomRangeFetch = () => {
    if (startDate && endDate) {
      fetchSalesReport();
    } else {
      setError('Please select both start and end dates.');
    }
  };

  const handleExport = (format) => {
    if (format === 'csv') {
      if (!reportData.orderBreakdown || reportData.orderBreakdown.length === 0) {
        console.warn('No order breakdown data to export.');
        return;
      }

      const getReportTitle = () => {
        const businessName = business?.settings?.name || 'Business';
        const periodMap = {
          today: 'Daily',
          weekly: 'Weekly',
          monthly: 'Monthly',
          all: 'All Time',
          custom: 'Custom Period'
        };
        const periodText = periodMap[period];
        return `${businessName} - ${periodText} Sales Report`;
      };

      const getDateRange = () => {
        if (period === 'custom' && startDate && endDate) {
          return `Period: ${new Date(startDate).toLocaleDateString()} to ${new Date(endDate).toLocaleDateString()}`;
        } else if (period === 'today') {
          return `Date: ${new Date().toLocaleDateString()}`;
        }
        return `Report Period: ${getPeriodLabel()}`;
      };

      // Create workbook with multiple sheets
      const wb = XLSX.utils.book_new();
      
      // Report Info Sheet
      const reportInfoData = [
        [getReportTitle()],
        [getDateRange()],
        [`Generated on: ${new Date().toLocaleString()}`],
        [],
        ['Generated by WisePOS']
      ];
      const wsInfo = XLSX.utils.aoa_to_sheet(reportInfoData);
      XLSX.utils.book_append_sheet(wb, wsInfo, "Report Info");

      // Summary Sheet
      const summaryData = [
        ['SALES SUMMARY'],
        [],
        ['Metric', 'Value'],
        ['Total Orders', reportData.summary.ordersCount],
        ['Total Revenue', FormatCurrency(reportData.summary.totalRevenue, currency)],
        ['Average Order Value', FormatCurrency(reportData.summary.averageOrderValue, currency)],
        ['Total Items Sold', reportData.orderBreakdown.reduce((total, item) => total + item.quantity, 0)]
      ];
      const wsSummary = XLSX.utils.aoa_to_sheet(summaryData);
      XLSX.utils.book_append_sheet(wb, wsSummary, "Summary");

      // Item Breakdown Sheet
      const itemBreakdownData = [
        ['ITEM BREAKDOWN'],
        [],
        ['Item Name', 'Category', 'Quantity Sold', 'Unit Price', 'Total Amount', '% of Revenue']
      ];
      
      reportData.orderBreakdown.forEach(item => {
        const percentageOfRevenue = reportData.summary.totalRevenue ? 
          ((item.totalAmount / reportData.summary.totalRevenue) * 100).toFixed(1) : '0.0';
        itemBreakdownData.push([
          item.name,
          item.category || '',
          item.quantity,
          FormatCurrency(item.unitPrice, currency),
          FormatCurrency(item.totalAmount, currency),
          `${percentageOfRevenue}%`
        ]);
      });
      const wsItems = XLSX.utils.aoa_to_sheet(itemBreakdownData);
      XLSX.utils.book_append_sheet(wb, wsItems, "Item Breakdown");

      // Category Breakdown Sheet
      const categoryBreakdownData = [
        ['CATEGORY BREAKDOWN'],
        [],
        ['Category', 'Items Sold', 'Total Revenue', '% of Total', 'Avg. Item Price']
      ];
      
      reportData.categorySales.forEach(category => {
        const percentageOfTotal = ((category.revenue / reportData.summary.totalRevenue) * 100).toFixed(1);
        categoryBreakdownData.push([
          category.name,
          category.itemsSold,
          FormatCurrency(category.revenue, currency),
          `${percentageOfTotal}%`,
          FormatCurrency(category.averagePrice, currency)
        ]);
      });
      const wsCategories = XLSX.utils.aoa_to_sheet(categoryBreakdownData);
      XLSX.utils.book_append_sheet(wb, wsCategories, "Category Breakdown");

      // Generate and download the Excel file
      const dateStr = new Date().toISOString().split('T')[0];
      const filename = `${business?.settings?.name || 'Business'}_${period}_sales_report_${dateStr}.xlsx`;
      
      // Write the workbook and trigger download
      XLSX.writeFile(wb, filename);

    } else if (format === 'pdf') {
      // Create new PDF document
      const pdf = new jsPDF();
      const businessName = business?.settings?.name || 'Business';
      const dateStr = new Date().toISOString().split('T')[0];
      
      // Helper function for period text
      const getPeriodText = () => {
        const periodMap = {
          today: 'Daily',
          weekly: 'Weekly',
          monthly: 'Monthly',
          all: 'All Time',
          custom: 'Custom Period'
        };
        return periodMap[period] || period;
      };

      // Header
      pdf.setFontSize(20);
      pdf.text(`${businessName}`, 14, 20);
      pdf.setFontSize(16);
      pdf.text(`${getPeriodText()} Sales Report`, 14, 30);
      
      // Date Range
      pdf.setFontSize(12);
      if (period === 'custom' && startDate && endDate) {
        pdf.text(`Period: ${new Date(startDate).toLocaleDateString()} to ${new Date(endDate).toLocaleDateString()}`, 14, 40);
      } else if (period === 'today') {
        pdf.text(`Date: ${new Date().toLocaleDateString()}`, 14, 40);
      } else {
        pdf.text(`Report Period: ${getPeriodLabel()}`, 14, 40);
      }
      
      // Summary Section
      pdf.setFontSize(14);
      pdf.text('Summary', 14, 55);
      
      const summaryData = [
        ['Total Orders', reportData.summary.ordersCount.toString()],
        ['Total Revenue', FormatCurrency(reportData.summary.totalRevenue, currency)],
        ['Average Order Value', FormatCurrency(reportData.summary.averageOrderValue, currency)],
        ['Total Items Sold', reportData.orderBreakdown.reduce((total, item) => total + item.quantity, 0).toString()]
      ];

      autoTable(pdf, {
        startY: 60,
        head: [['Metric', 'Value']],
        body: summaryData,
        theme: 'grid',
        headStyles: { fillColor: [41, 128, 185], textColor: 255 },
        margin: { top: 60 }
      });

      // Item Breakdown Section
      pdf.addPage();
      pdf.setFontSize(14);
      pdf.text('Item Breakdown', 14, 20);

      const itemData = reportData.orderBreakdown.map(item => {
        const percentageOfRevenue = reportData.summary.totalRevenue ? 
          ((item.totalAmount / reportData.summary.totalRevenue) * 100).toFixed(1) : '0.0';
        return [
          item.name,
          item.category || '',
          item.quantity.toString(),
          FormatCurrency(item.unitPrice, currency),
          FormatCurrency(item.totalAmount, currency),
          `${percentageOfRevenue}%`
        ];
      });

      autoTable(pdf, {
        startY: 30,
        head: [['Item Name', 'Category', 'Quantity', 'Unit Price', 'Total Amount', '% of Revenue']],
        body: itemData,
        theme: 'grid',
        headStyles: { fillColor: [41, 128, 185], textColor: 255 },
        margin: { top: 30 }
      });

      // Category Breakdown Section
      pdf.addPage();
      pdf.setFontSize(14);
      pdf.text('Category Breakdown', 14, 20);

      const categoryData = reportData.categorySales.map(category => {
        const percentageOfTotal = ((category.revenue / reportData.summary.totalRevenue) * 100).toFixed(1);
        return [
          category.name,
          category.itemsSold.toString(),
          FormatCurrency(category.revenue, currency),
          `${percentageOfTotal}%`,
          FormatCurrency(category.averagePrice, currency)
        ];
      });

      autoTable(pdf, {
        startY: 30,
        head: [['Category', 'Items Sold', 'Total Revenue', '% of Total', 'Avg. Item Price']],
        body: categoryData,
        theme: 'grid',
        headStyles: { fillColor: [41, 128, 185], textColor: 255 },
        margin: { top: 30 }
      });

      // Footer on all pages
      const pageCount = pdf.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        pdf.setPage(i);
        pdf.setFontSize(10);
        pdf.setTextColor(128);
        pdf.text(
          'Generated by WisePOS',
          pdf.internal.pageSize.width / 2,
          pdf.internal.pageSize.height - 10,
          { align: 'center' }
        );
        // Page numbers
        pdf.text(
          `Page ${i} of ${pageCount}`,
          pdf.internal.pageSize.width - 20,
          pdf.internal.pageSize.height - 10,
          { align: 'right' }
        );
      }

      // Save the PDF
      const filename = `${businessName}_${period}_sales_report_${dateStr}.pdf`;
      pdf.save(filename);
    }
  };

  const getPeriodLabel = () => {
    const labels = {
      today: 'Today',
      weekly: 'This Week',
      monthly: 'This Month',
      all: 'All Time',
      custom: 'Custom Range'
    };
    return labels[period] || 'Period';
  };

  return (
    <Container fluid className="mt-4">
      {/* Header */}
      <Row className="mb-4">
        <Col>
          <div className="d-flex justify-content-between align-items-center">
            <div>
              <h2 className="mb-1">Sales Report</h2>
              <p className="text-muted">
                {getPeriodLabel()} 
                {period === 'custom' && startDate && endDate && 
                  ` (${new Date(startDate).toLocaleDateString()} - ${new Date(endDate).toLocaleDateString()})`
                }
              </p>
            </div>
            <div>
              <Button 
                variant="outline-primary" 
                className="me-2"
                onClick={() => handleExport('csv')}
              >
                <FaDownload className="me-2" />
                Export CSV
              </Button>
              <Button 
                variant="primary"
                onClick={() => handleExport('pdf')}
              >
                <FaDownload className="me-2" />
                Export PDF
              </Button>
            </div>
          </div>
        </Col>
      </Row>

      {/* Filters */}
      <Card className="mb-4 shadow-sm">
        <Card.Body>
          <Row className="align-items-center">
            <Col md={8}>
              <div className="d-flex align-items-center">
                <p className="mb-0 me-3 text-muted">
                  <FaFilter className="me-2" />
                  Time Period:
                </p>
                <Tabs
                  activeKey={period}
                  onSelect={(k) => setPeriod(k)}
                  id="sales-period-tabs"
                  className="nav-pills-custom"
                >
                  <Tab eventKey="today" title="Today" />
                  <Tab eventKey="weekly" title="This Week" />
                  <Tab eventKey="monthly" title="This Month" />
                  <Tab eventKey="all" title="All Time" />
                  <Tab eventKey="custom" title="Custom Range" />
                </Tabs>
              </div>
            </Col>
          </Row>

          {period === 'custom' && (
            <Row className="mt-3">
              <Col md={4}>
                <Form.Group>
                  <Form.Label>Start Date</Form.Label>
                  <Form.Control
                    type="date"
                    value={startDate}
                    onChange={(e) => setStartDate(e.target.value)}
                  />
                </Form.Group>
              </Col>
              <Col md={4}>
                <Form.Group>
                  <Form.Label>End Date</Form.Label>
                  <Form.Control
                    type="date"
                    value={endDate}
                    onChange={(e) => setEndDate(e.target.value)}
                  />
                </Form.Group>
              </Col>
              <Col md={4} className="d-flex align-items-end">
                <Button 
                  variant="primary" 
                  onClick={handleCustomRangeFetch}
                  className="w-100"
                >
                  Apply Range
                </Button>
              </Col>
            </Row>
          )}
        </Card.Body>
      </Card>

      {/* Loading and Error States */}
      {loading && (
        <div className="text-center my-5">
          <Spinner animation="border" variant="primary" />
          <p className="mt-2">Loading sales report...</p>
        </div>
      )}

      {error && (
        <Alert variant="danger" className="text-center">
          {error}
        </Alert>
      )}

      {!loading && !error && (
        <Tabs defaultActiveKey="summary" className="mb-4">
          {/* Summary Tab */}
          <Tab eventKey="summary" title={
            <span>
              <FaChartBar className="me-2" />
              Summary
            </span>
          }>
            <Row className="mb-4">
              <Col md={3}>
                <Card className="text-center">
                  <Card.Body>
                    <Card.Title>Total Orders</Card.Title>
                    <h2 className="text-primary">{reportData.summary.ordersCount}</h2>
                    <Card.Text>Number of transactions</Card.Text>
                  </Card.Body>
                </Card>
              </Col>
              <Col md={3}>
                <Card className="text-center">
                  <Card.Body>
                    <Card.Title>Total Revenue</Card.Title>
                    <h2 className="text-success">
                      {FormatCurrency(reportData.summary.totalRevenue, currency)}
                    </h2>
                    <Card.Text>Gross sales amount</Card.Text>
                  </Card.Body>
                </Card>
              </Col>
              <Col md={3}>
                <Card className="text-center">
                  <Card.Body>
                    <Card.Title>Average Order Value</Card.Title>
                    <h2 className="text-info">
                      {FormatCurrency(reportData.summary.averageOrderValue, currency)}
                    </h2>
                    <Card.Text>Per transaction average</Card.Text>
                  </Card.Body>
                </Card>
              </Col>
              <Col md={3}>
                <Card className="text-center">
                  <Card.Body>
                    <Card.Title>Total Items Sold</Card.Title>
                    <h2 className="text-warning">
                      {reportData.orderBreakdown.reduce((total, item) => total + item.quantity, 0)}
                    </h2>
                    <Card.Text>All items combined</Card.Text>
                  </Card.Body>
                </Card>
              </Col>
            </Row>
          </Tab>

          {/* Order Breakdown Tab */}
          <Tab eventKey="breakdown" title={
            <span>
              <FaReceipt className="me-2" />
              Order Breakdown
            </span>
          }>
            <Card>
              <Card.Header>
                <h5 className="mb-0">Item-wise Sales Breakdown</h5>
              </Card.Header>
              <Card.Body className="p-0">
                <Table responsive striped hover>
                  <thead className="bg-light">
                    <tr>
                      <th>Item Name</th>
                      <th>Category</th>
                      <th className="text-center">Quantity Sold</th>
                      <th className="text-center">Unit Price</th>
                      <th className="text-end">Total Amount</th>
                      <th className="text-center">% of Revenue</th>
                    </tr>
                  </thead>
                  <tbody>
                    {reportData.orderBreakdown.map((item, index) => (
                      <tr key={index}>
                        <td>
                          <strong>{item.name}</strong>
                          {item.isTopSeller && (
                            <Badge bg="success" className="ms-2">Top Seller</Badge>
                          )}
                        </td>
                        <td>{item.category}</td>
                        <td className="text-center">{item.quantity}</td>
                        <td className="text-center">
                          {FormatCurrency(item.unitPrice, currency)}
                        </td>
                        <td className="text-end">
                          <strong>
                            {FormatCurrency(item.totalAmount, currency)}
                          </strong>
                        </td>
                        <td className="text-center">
                          {((item.totalAmount / reportData.summary.totalRevenue) * 100).toFixed(1)}%
                        </td>
                      </tr>
                    ))}
                  </tbody>
                  <tfoot className="bg-light">
                    <tr>
                      <td colSpan="4" className="text-end">
                        <strong>Grand Total:</strong>
                      </td>
                      <td className="text-end">
                        <strong>
                          {FormatCurrency(reportData.summary.totalRevenue, currency)}
                        </strong>
                      </td>
                      <td className="text-center">100%</td>
                    </tr>
                  </tfoot>
                </Table>
              </Card.Body>
            </Card>
          </Tab>

          {/* Category Sales Tab */}
          <Tab eventKey="categories" title="Categories">
            <Card>
              <Card.Header>
                <h5 className="mb-0">Sales by Category</h5>
              </Card.Header>
              <Card.Body className="p-0">
                <Table responsive striped hover>
                  <thead className="bg-light">
                    <tr>
                      <th>Category</th>
                      <th className="text-center">Items Sold</th>
                      <th className="text-end">Total Revenue</th>
                      <th className="text-center">% of Total</th>
                      <th className="text-center">Avg. Item Price</th>
                    </tr>
                  </thead>
                  <tbody>
                    {reportData.categorySales.map((category, index) => (
                      <tr key={index}>
                        <td>
                          <strong>{category.name}</strong>
                        </td>
                        <td className="text-center">{category.itemsSold}</td>
                        <td className="text-end">
                          {FormatCurrency(category.revenue, currency)}
                        </td>
                        <td className="text-center">
                          {((category.revenue / reportData.summary.totalRevenue) * 100).toFixed(1)}%
                        </td>
                        <td className="text-center">
                          {FormatCurrency(category.averagePrice, currency)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </Table>
              </Card.Body>
            </Card>
          </Tab>
        </Tabs>
      )}
    </Container>
  );
};

export default SalesReport;



//   const handleExport = async (format) => {
//     try {
//       setLoading(true);
//       setError('');

//       const params = period === 'custom' ? { startDate, endDate, format } : { period, format };
      
//       // Assuming 'api' is your configured axios instance
//       const response = await getSalesReport(params, {
//         responseType: 'blob', // This is important to handle the file download
//       });

//       // Create a URL for the blob
//       const url = window.URL.createObjectURL(new Blob([response]));
//       const link = document.createElement('a');
//       link.href = url;
      
//       // Set the download filename
//       link.setAttribute('download', `sales-report.${format}`);
      
//       // Append to the document, click, and then remove
//       document.body.appendChild(link);
//       link.click();
//       link.parentNode.removeChild(link);

//     } catch (err) {
//       console.error('Failed to export sales report:', err);
//       setError('Unable to export sales report. Please try again later.');
//     } finally {
//       setLoading(false);
//     }
//   };
// Also, you will need to update your getSalesReport function in api.jsx to handle the export case. It should look something like this:

// export const getSalesReport = async (params, config = {}) => {
//     try {
//         const response = await api.get('/sales/report', {
//             params,
//             ...setAuthHeader(),
//             ...config, // Pass additional config like responseType
//         });
//         return response.data;
//     } catch (error) {
//         handleApiError(error);
//         throw error.response.data;
//     }
// };
// This should make the export functionality work. Let me know if you have any other questions.

